stages:
  - build
#  - test

default:
#  image: registry.hzdr.de/llrf/ctk-docker/ctk-application-opc-ua:xenial
  image: registry.hzdr.de/llrf/ctk-docker/ctk-application-opc-ua_root:xenial
build_package:
  stage: build
#  artifacts:
#    paths:
#      - build
#    expire_in: 1 day
  script:
    - apt update
    - apt install libchimeratk-daq
    - mkdir build
    - cd build
    - cmake -DADAPTER=OPCUA ..
    - make


#run_tests:
#  stage: test
#  script:
#    - make test
